env:
  browser: true
  es6: true
  jest/globals: true
parser: babel-eslint
extends: 
  - 'airbnb-base'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
  - babel
  - jest
rules:
  indent:
    - error
    - 2
  import/no-unresolved: off
  react/prop-types: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
settings:
  react:
    version: 16.8.3
