env:
  browser: true
  es6: true
  jest/globals: true
parser: babel-eslint
extends: 
  - 'airbnb-base'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
  - babel
  - jest
rules:
  react/prop-types: off
settings:
  react:
    version: 16.8.3
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
